name: CML Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Give the token the rights needed for comments on commits and PRs
permissions:
  contents: write
  pull-requests: write

jobs:
  train-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: python train.py

      - name: Build CML report
        run: |
          echo "## Métriques du modèle" > report.md
          echo "" >> report.md
          cat metrics.json >> report.md

      - name: Install CML
        run: npm install -g @dvcorg/cml

      # Comment PRs from same repo
      - name: Comment PR with CML
        if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork }}
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create --pr report.md

      # Comment commits on pushes
      - name: Comment commit with CML
        if: ${{ github.event_name == 'push' }}
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create --commit-sha "$GITHUB_SHA" report.md

      # Skip forked PRs (no write perms/secrets)
      - name: Skip comment for forked PR
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}
        run: echo "Forked PR: skipping CML comment (no permissions)."
